export const productsData = [
  {
    id: 1,
    icon: require('@assets/images/articles/burger.jpeg'),
    imageUrl: '@assets/images/articles/burger.jpeg',
    foodname: 'Burgers',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '20',
    rating: 5,
    reviews: 100,
  },
  {
    id: 2,
    icon: require('@assets/images/articles/icecream.jpeg'),
    imageUrl: '@assets/images/articles/icecream.jpeg',
    foodname: 'Waffles',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '30',
    rating: 3,
    reviews: 10,
  },
  {
    id: 3,
    icon: require('@assets/images/articles/nachos.jpeg'),
    imageUrl: '@assets/images/articles/nachos.jpeg',
    foodname: 'Nachos',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '50',
    rating: 4,
    reviews: 40,
  },
  {
    id: 4,
    icon: require('@assets/images/articles/dhakachicken.jpeg'),
    imageUrl: '@assets/images/articles/dhakachicken.jpeg',
    foodname: 'Dhaka Chicken',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '10',
    rating: 4,
    reviews: 130,
  },
  {
    id: 5,
    icon: require('@assets/images/articles/buttermilkwaffles.jpeg'),
    imageUrl: '@assets/images/articles/buttermilkwaffles.jpeg',
    foodname: 'ButterMilk Waffles',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '80',
    rating: 3,
    reviews: 138,
  },
  {
    id: 6,
    icon: require('@assets/images/articles/pancakes.jpeg'),
    imageUrl: '@assets/images/articles/pancakes.jpeg',
    foodname: 'Pan Cakes',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '60',
    rating: 2,
    reviews: 160,
  },
  {
    id: 7,
    icon: require('@assets/images/articles/steaks.jpeg'),
    imageUrl: '@assets/images/articles/steaks.jpeg',
    foodname: 'Steaks',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '45',
    rating: 4,
    reviews: 44,
  },
  {
    id: 8,
    icon: require('@assets/images/articles/pizza.jpeg'),
    imageUrl: '@assets/images/articles/pizza.jpeg',
    foodname: 'Pizza',
    types: [
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
      'Margherita',
    ],
    addons: ['Pommes', 'Kroketten', 'Reis', 'Nudeln', 'Salat'],
    price: '55',
    rating: 3,
    reviews: 100,
  },
];

// menuitems.tsx
export const menuItems = [
  {
    menuTitle: 'Breakfast Good Deals!',
    menuSubtitle: 'Discount upto',
    backgroundImage: require('@assets/images/deals/breakfast.jpeg'), // Replace with the actual path to your image
    discount: '60%',
  },
  {
    menuTitle: 'Lunch Good Deals!',
    menuSubtitle: 'Discount upto',
    backgroundImage: require('@assets/images/deals/lunch.jpeg'), // Replace with the actual path to your image
    discount: '50%',
  },
  {
    menuTitle: 'Dinner Good Deals!',
    menuSubtitle: 'Discount upto',
    backgroundImage: require('@assets/images/deals/dinner.jpeg'), // Replace with the actual path to your image
    discount: '20%',
  },
];

export const categoryItems = [
  {
    categoryTitle: 'Pizza',
    backgroundImage: require('@assets/images/categories/pizza-r.png'),
    bgColor: '#666EE3',
  },
  {
    categoryTitle: 'Reis',
    backgroundImage: require('@assets/images/categories/rice-r.png'),
    bgColor: '#E38E72',
  },
  {
    categoryTitle: ' Pasta',
    backgroundImage: require('@assets/images/categories/pasta-r.png'),
    bgColor: '#72A9E3',
  },
  {
    categoryTitle: 'Meat Menus',
    backgroundImage: require('@assets/images/categories/meat-r.png'),
    bgColor: '#86E372',
  },
  {
    categoryTitle: 'Appetizers',
    backgroundImage: require('@assets/images/categories/appetizers-r.png'),
    bgColor: '#BE72E3',
  },
  {
    categoryTitle: 'Salad',
    backgroundImage: require('@assets/images/categories/salad-r.png'),
    bgColor: '#FEC381',
  },
  {
    categoryTitle: 'Drinks',
    backgroundImage: require('@assets/images/categories/drinks-r.png'),
    bgColor: '#81FED1',
  },
  {
    categoryTitle: 'Desserts',
    backgroundImage: require('@assets/images/categories/desserts-r.png'),
    bgColor: '#FE81F8',
  },
  {
    categoryTitle: 'Indian Specials',
    backgroundImage: require('@assets/images/categories/indianspecials-r.png'),
    bgColor: '#81B3FE',
  },
  {
    categoryTitle: 'Dips and Sauces',
    backgroundImage: require('@assets/images/categories/dips-r.png'),
    bgColor: '#FFC24B',
  },
  {
    categoryTitle: 'Steaks',
    backgroundImage: require('@assets/images/categories/steaks-r.png'),
    bgColor: '#66D1E3',
  },
];
